- source/lang-php.rst
> remove PHP 5.6, 7.0

- source/lang-nodejs.rst
> node v9 is no longer available

- source/web-tor.rst
… and capitalise Tor since it's a proper name
> Fix typos in Tor page

- source/background-network.rst
https://twitter.com/JMoVS/status/1125800765585547265/photo/1
> : pencil2: add a missing you to background-network.rst

- source/conf.py
This should fix the "Edit on GitHub" link
> Fix " Edit on GitHub" link

- source/includes/domain-idn.txt
> explain how to convert domains to idn

- source/index.rst
https://clarkwp.wordpress.com/2014/04/30/why-is-the-p-in-wordpress-important/
> The capital P

- source/changelog/2019-08-21_7.3.5.2.rst
> add changelog for 7.3.5.2

- source/web-https.rst
I'll use this as a chance to praise your awesome work! I love using Uberspace and your docs are great. Thanks for the great work, keep it up! :tada: :heart:
> Fix spelling

- source/basics-shell.rst
See also: https://manual.uberspace.de/changelog_archive.html#id89
> Add fish to the list of supported shells

- source/basics-ssh.rst
> Add modern Windows 10 to the OpenSSH section as a supported operating system

- source/lang-dotnet.rst
And also clarify our version / update policy a bit (we don't remove old versions).
> :heavy_plus_sign: update dotnet core to 3.1

- source/mail-domains.rst
- source/mail-filter.rst
> Revert "Fix typos"

- source/database-mysql.rst
I had to go googling for this information.  Helps when you want to see what DBs aren't in use anymore, so they can be deleted.
Hey, please check my rst syntax!  I've never used it.
> Added instructions to list additional databases

- source/database-mysql.rst
See https://github.com/Uberspace/manual/issues/126
> :pencil: add mysql password requirements #126

- source/mail-mailboxes.rst
See https://github.com/Uberspace/manual/issues/127
> :pencil: add mailbox password requirements #127

- source/changelog/2020-03-25_7.5.rst
a try on the lost changelog for `v7.5`
> add release notes for `v7.5`

- source/mail-mailboxes.rst
An attempt at https://github.com/Uberspace/manual/issues/147
> explain password score for mailbox passwords #147

- source/changelog/2020-05-07_7.6.1.1.rst
rolling out today (2020-05-07)
> add changelog for v7.6.1.1

- source/changelog/2020-05-12_7.6.1.2.rst
Rollout for it will start tomorrow (2020-05-12).
> add changelog for v7.6.1.2

- source/index.rst
- source/uberspace2uberspace.rst
> link to uberspace 6 migration docs

- source/mail-mailboxes.rst
see https://github.com/Uberspace/manual/pull/183#issuecomment-662435762
> :pencil2: change inclusive phrasing

- source/changelog/2020-07-28_7.7.2.rst
starting to roll out today (2020-07-28).
> add changelog for 7.7.2

- source/web-documentroot.rst
Talked about this with nico because I did run into this issue and was a bit confused :)
> Explain SELinux permissions in web documentation

- source/web-tor.rst
documenting possibility for redirect to Onion Location
> on Onion Location

- source/web-tor.rst
* working syntax for uberspace tool
* hint on meta overriding http header
> fix web header syntax

- source/background-http-stack.rst
Hey @uberspace,
while reading this manual page I noticed a typo. This PR is to fix that.
Thank you for your great service and have a great week!
> Fix typo in background-http-stack.rst

- source/mail-forwarding.rst
- source/mail-spam.rst
score has been adjusted in [7.7.3] - 2020-08-10
> change rspamd score from 15 to 10

- source/_static/css/custom.css
remove paddings in highlighting
> remove css paddings in highlighting

- source/web-documentroot.rst
> Fix small spelling mistake in web-documentroot.rst

- source/lang-rust.rst
Hello! Just quick drive-by typo fix.
Thank you for your awesome docs!
> Fix typo on rust page

- source/background-network.rst
changed $USERNAME to $USER, since $USERNAME is not set by default.
> fix locally reachable only hostname

- source/billing-general.rst
> :fire: remove info about additional storage limited to 20gb

- source/mail-domains.rst
see https://manual.uberspace.de/changelog/#changed
> update SPF record example

- source/mail-filters.rst
> use X-Rspamd-Score instead of x-Spam-score

- source/mail-filters.rst
- fixed some typos
- changed headers hierarchy
- moved spamfolder hint up and fix link to manual page
- simplified symlink code
- changed textes
> Sieve improve

- source/changelog/2021-05-03_7.11.1.rst
supposed to start rolling out on 2021-05-03
> Feature/changelog 7.11.1

- source/mail-forwarding.rst
Already stumbled about this in #248. Happened again, docs are still not great. I think I finally found a description that feels good.
> Clearify difference between regular mailboxes and forwards

- source/changelog/2021-06-15_7.11.3.rst
small release, started rolling out earlier today…
> :memo: add changelog for v7.11.3

- source/mail-filters.rst
> remove 'comparator "i;ascii-numeric'

- source/mail-forwarding.rst
see https://github.com/Uberspace/manual/pull/329
> add link to catchall at forward delete

- source/web-documentroot.rst
> add chmod example for docroots #239

- source/mail-spam.rst
> add autoexpunge info for spamfolder #295

- source/mail-filters.rst
specify for what managesieve is used 
closes #317
> improve managesieve text #317

- source/lang-nodejs.rst
> update nodejs version #157

- source/changelog/2021-08-19_7.11.4.rst
- source/lang-erlang.rst
- source/lang-nodejs.rst
- source/lang-python.rst
- source/mail-access.rst
- source/mail-domains.rst
> :rocket: add changes for Uberspace version  [U7.11.4]

- source/database-mysql.rst
> make an explicit warning to change the password in .my.cnf #136

- source/web-documentroot.rst
> add an example for docroot #269

- source/lang-java.rst
> update java version to 16

- source/mail-access.rst
> Mail access

- source/basics-ssh.rst
- source/putty.rst
> Move putty to separate article

- source/_templates/layout.html
> fix changelog.atom path

- source/web-backends.rst
This should also fix highlighting
> Fix indentation

- source/lang-dotnet.rst
hey there,
added new dotnet version 6.0.2 to manual.
regards
> add new dotnet 6.0.2

- source/basics-ssh.rst
fix https://github.com/Uberspace/manual/issues/407
> rework ssh article and compress it to basic info

- source/web-headers.rst
src & proof: https://blog.google/products/chrome/get-know-new-topics-api-privacy-sandbox/
and please fix my typo there... "method..."
> Note on Google renaming FLoC to Google Topics

- source/mail-filters.rst
Don't merge until next U7 release.
closes #428
> WIP: Sieve vacation auto reply

- source/daemons-supervisord.rst
- source/includes/daemons-supervisord-reread-update.rst
- source/includes/daemons-supervisord-start-stop.rst
- source/includes/web-backend.rst
- source/lang-nodejs.rst
I struggled a bit to get my node application running. I did not know how to configure the daemon correctly. So I added an example tot the docs.
I tested the daemon settings with a node fastify application
> Add daemon description to nodejs

- source/changelog/2022-08-08_7.13.rst
> Update 2022-08-08_7.13.rst Typo

- source/basics-ports.rst
> fix typo on ports page 

- source/mail-mailboxes.rst
> add some more info to mail plus adressing

- source/lang-nodejs.rst
- source/lang-ruby.rst
> 526 remove nodejs19 deprecate nodejs16 deprecate ruby 27

- source/changelog/2023-12-11_7.15.8.rst
- source/lang-nodejs.rst
- source/lang-ruby.rst
> [U7.15.8] add changelog and manual changes

- source/database-mysql.rst
Hi,
I think you're at version 10.6 now. 🙂
Regards,
Tobias
> Update version of MariaDB

- source/mail-mailboxes.rst
When looking something up I noticed the links do not work.
Thanks for the very helpful manual!
> Fix broken links to mail-filters

- source/mail-filters.rst
> [mail-filters] missing variable in vacation script

- source/firstday-ubernauts.rst
> [firstday-ubernauts] rm note about U6-to-U7 migrations

- source/lang-dotnet.rst
> dotnet 8 will not be released for RHEL 7
