- source/background-network.rst
Fixed the hyperlink on the Backround/Network page referencing the Ubuntu docs.
All other hyperlinks seem to be correct.
> Fix hyperlink to port forwarding docs

- source/web-https.rst
I think "once" was the intention of the author.
> Fix typo: one a month -> once a month

- source/background-network.rst
ppl love to misspell this one 'cos of its phonetics.
German mnemonic: "Separee" (private room)
> typo "separated"

- source/changelog/2020-03-23_7.4.5.rst
We never released `v7.4.5`, changes are included in `v7.5`; see [137](https://github.com/Uberspace/manual/pull/137/files).
> remove changelog for `v7.4.5`

- source/changelog/2020-05-25_7.6.2.rst
Rollout starts Monday, 2020-05-25 (week 22).
> add changelog for v7.6.2

- source/web-https.rst
I was totally misunderstanding this sentence and I believe this change makes it much more obvious what's happening. Assuming I understand it now.
> danke! Ich wollte gerade vorschlagen, ob man diesen Satz nicht in die Doku aufnehmen kann. Dann ist mir aufgefallen, es ist genau der Satz, den ich zuvor zitiert habe. Die Wortwahl ist nur sehr ungünstig. Bei "domain is requested by a client" bin ich davon ausgegangen, dass ich (der Client, euer Kunde) die Domain "requeste" also via "web domain add" hinzufüge. Man würde im Falle eines HTTP Clients o.ä. ja nicht davon reden, dass eine Domain requested wird. Zumindest ist mir die Formulierung so noch nicht begegnet.
> Improve automagic HTTPS docs

- source/mail-mailboxes.rst
Following many other projects and companies, I suggest using words like "allow list" and "deny list" over "white-" and "blacklist". (see e.g. https://www.heise.de/news/Nichtrassistische-Sprache-Abschied-von-Blacklist-und-Whitelist-4784291.html)
>  replaced term "blacklist"

- source/mail-access.rst
Following many other projects and companies, I suggest using words like "allow list" and "deny list" over "white-" and "blacklist". (see e.g. https://www.heise.de/news/Nichtrassistische-Sprache-Abschied-von-Blacklist-und-Whitelist-4784291.html)
> replaced term "white list" with "allow list"

- source/changelog.rst
- source/changelog_archive.rst
- source/includes/hotfix-version.rst
- source/index.rst
While we try to be thorough, not every hotfix might show up in our changelog. This adds a note to explain that.
> :pencil: explain possibility of missing notes for hotfixes

- source/changelog/2020-08-17_7.7.4.rst
Rollout for `v7.7.4` has started today.
> add CHANGELOG for `v7.7.4`

- source/lang-erlang.rst
Add Erlang version `23` to the list. 
It is included in `v7.7.4`, which starts rolling out today.
> add Erlang 23

- source/daemons-supervisord.rst
I spend the afternoon yesterday to debug a particular problem with a service and couldn't see any error message. I contacted uberspace support (ticket [Uberspace.de #480399]) and Nico was so kind to email me back how to check ``stderr`` logs with ``supervisorctl``. Hope this helps other developers in the future.
> docs: Check ``stderr` with ``supervisorctl``

- source/index.rst
This reverts commit 429c55a4d7acc486f95ca672660f172a2a354818.
While I released the docs too early, deno support will come. We have to wait till the next release though.
> Revert ":fire: rm deno docs from index"

- source/web-documentroot.rst
updated documentroot default configuration and add a hint to the `httpd.conf` file on the host. Maybe it isn't necessary at all to show the plain (incomplete) configs within the manual, we could point out to the original config file only.
> update httpd default config

- source/basics-resources.rst
Fixed the outdated output of `quota -gsl` and cleaned up the text.
The page and text still needs to be updated afterwards to reflect the new additional storage https://twitter.com/ubernauten/status/1321482024406949890
> fix quota code and clean up the text a bit

- source/lang-php.rst
We will deprecate PHP 7.2 with the next release (probably `7.8.1` ~ 2020-12-14).
> :fire: deprecate PHP 7.2

- source/basics-resources.rst
It would helpful to see the information for extra storage before the explanations of the limitations. Move it from the bottom to the top.
> Move extra storage note to the top

- source/changelog/2020-12-22_7.8.1.rst
Version `7.8.1` started to roll out on production hosts today. Here's a quick write up of the relevant changes.
> :pencil: add release notes for v7.8.1

- source/firstday-ubernauts.rst
Fixed a typo to correctly link to the page regarding opening ports.
Note: I'm not sure why GitHub shows a change in line 110. I didn't change anything there.
> Fixed typo in link

- source/firstday-ubernauts.rst
- source/u6-namespaces.rst
because we have to interfere into the users mailbox namespaces when auto migrating to U7, we should tell them the backgrounds and how to solve it
> create verbose u6-namespace description

- source/web-headers.rst
- adds an example section to web-headers.rst
- adds blocking google FLoC with HTTP headers to that section
Google FLoC is the new [as of 04/2021] way of google to track users. this documents how to block that on a site on an uberspace.
> web-headers: add blocking google FLoC as example

- source/lang-python.rst
Python version 3.9 is missing in the manual.
> Updates available Python versions

- source/web-logs.rst
The IP address in the access log comes right after the hostname + port
> fix ip address in description of access log format

- source/mail-forwarding.rst
to be hones, the old text was not so bad, but some users might have misunderstood it as "delete all your .qmail immediately files because it is broken" the updated text is IMHO a bit verbose, youre decision @nichtmax
> update qmail warning #320

- source/web-domains.rst
Note explicitly that domain is compared with web and mail domains of other accounts.
(I just tried to add a subdomain to the web configuration of a second account, deleted the main domain from the web config of the first account and still got the error message. Took me a few minutes to figure out that I had to delete the main domain from the mail configuration, as well.)
Also fixes a few typos.
> Note on error when trying to add subdomain

- source/mail-access.rst
Remove the Apple Mail.app section - Apple deleted the article, so the link was dead and the underlying problem doesn't seem to occur anymore either.
> :fire: fix dead link in mail-access.rst

- source/billing-general.rst
Former Sparkasse Mainz and Sparkasse Worms-Alzey-Ried merged into Rheinhessen Sparkasse, resulting in a new IBAN and BIC.
> Update bank account information

- source/mail-filters.rst
Using "i;ascii-numeric" for spam score check, as default comparison gives wrong results for values greater than 10
> Use numeric comparison in Sieve filter example

- source/lang-ruby.rst
This will roll out no later than together with Uberspace version `7.14` (no release date yet).
> [7.14] add Ruby 3.1

- source/lang-erlang.rst
This will roll out no later than together with Uberspace version `7.14` (no release date yet).
> [7.14] add Erlang OTP 25

- source/database-mongodb.rst
Add MongoDB 6.0 and deprecate `4.0`. This will roll out no later than together with Uberspace version `7.14` (no release date yet).
> [7.14] add MongoDB 6.0

- source/mail-filters.rst
Reverts Uberspace/manual#444
`i;ascii-numeric` is a really bad idea as it can't handle signed numerics, so `-5.6` is interpreted the same as `5.6` and both are treated as spam.
> Revert "Use numeric comparison in Sieve filter example"

- source/mail-filters.rst
The previous rule lead to messages with negative spam score lower than –4 to be considered SPAM because apparently i;ascii-numeric does not handle negative numbers. 
Edit: Only now did I find issue #363 – this PR would resolve that issue.
cf. https://doc.dovecot.org/configuration_manual/sieve/examples/#direct-filtering-using-message-header  
»Be very careful when matching against spam score headers using the relational extension and the i;ascii-numeric comparator. This comparator can only be used to match unsigned integers. Strings that do not begin with a digit character represent positive infinity and will therefore always be larger than any score mentioned in your rule! That is why the above example first checks the minus sign explicitly.«
> Make sure the Spam-score is not negative

- source/mail-filters.rst
Old URL (https://www.fastmail.com/cgi-bin/sievetest.pl) does no longer function (404)
> Updated URL of Fastmail's Sieve Tester

- source/lang-python.rst
The page used to contain a hardcoded link which probably broken when the url scheme was updated from `/lang-python/` to `/lang-python.html`.
> Fix broken link in lang-python

- source/mail-access.rst
Add an explicit example and counter-example, mentioning the certificate problem if not respected.
> mail-access.rst: Be more explicit about the hostname

- netlify.toml
the redirect corrupts the prettified .html forwards
> disabled 404 redirects for now

- source/lang-php.rst
PHP 8.0 is end of life and will be deprecated. I guess we can update the examples to PHP 8.1.
> replace php version 8.0 with 8.1

- source/migration/qmail/reports/config-is-catchall.rst
The description text mentions `shops-*@` as example e-mail, but the sieve code uses `hallo-*@`. This commit brings both back in sync by using `shops-*@` consistently.
> config-is-catchall: fix example out of sync with description

- source/lang-php.rst
With the successful vote on https://wiki.php.net/rfc/release_cycle_update, the support period for PHP versions has changed: https://www.php.net/supported-versions.php
> Correction of the support periods of the available PHP versions

- source/basics-resources.rst
It is not quite obvious that 'quota' needs an interactive shell, and it is not documented in the manpage either. Let's document it here instead.
> Mention dependency for quota in basic-resources

- source/mail-domains.rst
Most users - myself included - don't read the entire manual page, but they immediately jump to the section that's relevant for their current question. I just spent quite some time finding the right DKIM record instructions because they were mentioned above in another section. So I added a convenient reference so that others will get there faster than myself :-)
> Improved DKIM instructions
